package com.example.myapplication


val Token="Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJDb3VyaWVyIEFiZG8iLCJVc2VySUQiOiIzMTY1IiwiUm9sZUlEIjoiNSIsImV4cCI6MTY5NjA4Mjg2MywiaXNzIjoiR1QiLCJhdWQiOiJHVCJ9.EnHo-Yf3AoOJHKAbm48VU2-7EQsenORmCtbSIBVMyHA"
val BaseUrl="http://test.redexpresseg.com/api/APIs/"