package com.example.myapplication


val Token="Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBaG1lZCBBbWlyIENvdXJpZXIiLCJVc2VySUQiOiIzMTY2IiwiUm9sZUlEIjoiNSIsImV4cCI6MTY5NDQ4MjEwNywiaXNzIjoiR1QiLCJhdWQiOiJHVCJ9.fOFouxHPbX2sm4fzNQTXunbBGJUysphPcLuaaHO_Z8M"
val BaseUrl="http://test.redexpresseg.com/api/APIs/"